#!/bin/bash

set -x

# Manually define aliases if snap isn't installed from snap store.
# Otherwise, snap store defines these aliases automatically.
snap aliases nova-hypervisor | grep neutron-ovs-cleanup || \
    sudo snap alias nova-hypervisor.neutron-ovs-cleanup neutron-ovs-cleanup
snap aliases nova-hypervisor | grep neutron-netns-cleanup || \
    sudo snap alias nova-hypervisor.neutron-netns-cleanup neutron-netns-cleanup

sudo neutron-ovs-cleanup
sudo neutron-netns-cleanup

snaps="database keystone nova neutron glance cinder nova-hypervisor neutron-ext-net"

for snap in $snaps; do
    sudo snap remove $snap
done

sudo mysql -u root << EOF
DROP DATABASE keystone;
DROP DATABASE nova;
DROP DATABASE nova_api;
DROP DATABASE nova_cell0;
DROP DATABASE neutron;
DROP DATABASE glance;
DROP DATABASE cinder;
EOF

sudo rabbitmqctl delete_user openstack

# Clean up the cinder volume group and file-based loopback device
sudo lvremove -f cinder-volumes
sudo vgremove -f cinder-volumes
loop_dev=$(sudo losetup -j /var/cinder/cinder-volumes-file | awk -F':' '/'cinder-volumes-file'/ { print $1}')
[ -n $loop_dev ] || sudo losetup -d $loop_dev
[ -e /var/cinder/cinder-volumes-file ] && sudo rm /var/cinder/cinder-volumes-file
