#!/bin/bash

set -x

# Manually define aliases if snap isn't installed from snap store.
# Otherwise, snap store defines these aliases automatically.
snap aliases nova-hypervisor | grep neutron-ovs-cleanup || \
    sudo snap alias nova-hypervisor.neutron-ovs-cleanup neutron-ovs-cleanup
snap aliases nova-hypervisor | grep neutron-netns-cleanup || \
    sudo snap alias nova-hypervisor.neutron-netns-cleanup neutron-netns-cleanup

sudo neutron-ovs-cleanup
sudo neutron-netns-cleanup

snaps="database keystone nova neutron glance nova-hypervisor neutron-ext-net"

for snap in $snaps; do
    sudo snap remove $snap
done

sudo mysql -u root << EOF
DROP DATABASE keystone;
DROP DATABASE nova;
DROP DATABASE nova_api;
DROP DATABASE nova_cell0;
DROP DATABASE neutron;
DROP DATABASE glance;
DROP DATABASE cinder;
EOF

sudo rabbitmqctl delete_user openstack
