#!/bin/bash
#
# A script for testing OpenStack snap packages on a single node.
# The node is expected to be Ubuntu 16.04 (xenial).
#

set -ex

sudo apt update
DEBIAN_FRONTEND='noninteractive' sudo apt install --yes python3-openstackclient rabbitmq-server mysql-server \
    memcached libvirt-bin qemu-kvm apparmor-utils

# See https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1644507
sudo aa-complain /usr/lib/libvirt/virt-aa-helper

SCRIPT=$(readlink -f $0)
export BASE_DIR=$(dirname $SCRIPT)

scripts/database.sh
scripts/keystone.sh
scripts/nova.sh
scripts/neutron.sh
scripts/glance.sh
