#!/bin/bash

set -x

snaps="database keystone nova neutron glance nova-hypervisor neutron-ext-net"

for snap in $snaps; do
    sudo snap remove $snap
done

sudo mysql -u root << EOF
DROP DATABASE keystone;
DROP DATABASE nova;
DROP DATABASE nova_api;
DROP DATABASE nova_cell0;
DROP DATABASE neutron;
DROP DATABASE glance;
DROP DATABASE cinder;
EOF

sudo rabbitmqctl delete_user openstack
