#!/bin/bash
#
# A script for testing OpenStack snap packages on a single node.
#

set -ex

sudo apt update
DEBIAN_FRONTEND='noninteractive' sudo -E apt install --yes python3-openstackclient rabbitmq-server mysql-server \
    memcached libvirt-bin qemu-kvm apparmor-utils

# See https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1644507
sudo aa-complain /usr/lib/libvirt/virt-aa-helper

SCRIPT=$(readlink -f $0)
export BASE_DIR=$(dirname $SCRIPT)

scripts="database keystone nova neutron glance"

for script in $scripts; do
    scripts/$script.sh
done
